# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PyCode\PyQT5\Sushi's Tiny Adveture GUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class QandA:

    def __init__(self):

        super().__init__()

        self.tellme  # Adding () mess this over

    # adding the .tellme, notice that the txt file i most use is set by default.
    def tellme(self, key, story='story.txt'):

        self.story = story
        self.story = open(story, "r")

        content = self.story.readlines()
        content = [x.strip() for x in content]

        self.key = key - 1  # This mamkes it so the key alings with the rows in the txt file

        self.story.close()

        return content[self.key]


qna = QandA()  # Definig QnadA as qna

# qna.tellme(NUM)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 600))
        MainWindow.setMaximumSize(QtCore.QSize(2500, 3000))
        MainWindow.setStyleSheet("")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")


        self.storyStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.storyStackedWidget.setMinimumSize(QtCore.QSize(0, 450))
        self.storyStackedWidget.setObjectName("storyStackedWidget")


        self.page_1_quest1_2 = QtWidgets.QWidget()
        self.page_1_quest1_2.setObjectName("page_1_quest1_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_1_quest1_2)
        self.verticalLayout.setObjectName("verticalLayout")


        self.label1 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setAutoFillBackground(False)
        self.label1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1.setMidLineWidth(-2)
        self.label1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)


        self.label2 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setAutoFillBackground(False)
        self.label2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2.setMidLineWidth(-2)
        self.label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label2.setObjectName("label2")
        self.verticalLayout.addWidget(self.label2)


        self.label3 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setAutoFillBackground(False)
        self.label3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3.setMidLineWidth(-2)
        self.label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label3.setObjectName("label3")
        self.verticalLayout.addWidget(self.label3)


        self.label4 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setAutoFillBackground(False)
        self.label4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4.setMidLineWidth(-2)
        self.label4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label4.setObjectName("label4")
        self.verticalLayout.addWidget(self.label4)


        self.label5 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setAutoFillBackground(False)
        self.label5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5.setMidLineWidth(-2)
        self.label5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label5.setObjectName("label5")
        self.verticalLayout.addWidget(self.label5)


        self.label6 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6.sizePolicy().hasHeightForWidth())
        self.label6.setSizePolicy(sizePolicy)
        self.label6.setAutoFillBackground(False)
        self.label6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6.setMidLineWidth(-2)
        self.label6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label6.setObjectName("label6")
        self.verticalLayout.addWidget(self.label6)


        self.label7 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7.sizePolicy().hasHeightForWidth())
        self.label7.setSizePolicy(sizePolicy)
        self.label7.setAutoFillBackground(False)
        self.label7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7.setMidLineWidth(-2)
        self.label7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label7.setObjectName("label7")
        self.verticalLayout.addWidget(self.label7)
        self.label8 = QtWidgets.QLabel(self.page_1_quest1_2)


        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8.sizePolicy().hasHeightForWidth())
        self.label8.setSizePolicy(sizePolicy)
        self.label8.setAutoFillBackground(False)
        self.label8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8.setMidLineWidth(-2)
        self.label8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label8.setObjectName("label8")
        self.verticalLayout.addWidget(self.label8)


        self.label9 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9.sizePolicy().hasHeightForWidth())
        self.label9.setSizePolicy(sizePolicy)
        self.label9.setAutoFillBackground(False)
        self.label9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9.setMidLineWidth(-2)
        self.label9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label9.setObjectName("label9")
        self.verticalLayout.addWidget(self.label9)


        self.label10 = QtWidgets.QLabel(self.page_1_quest1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10.sizePolicy().hasHeightForWidth())
        self.label10.setSizePolicy(sizePolicy)
        self.label10.setAutoFillBackground(False)
        self.label10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10.setMidLineWidth(-2)
        self.label10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)

        self.label10.setObjectName("label10")
        self.verticalLayout.addWidget(self.label10)


        self.ButtonUpperSpace_2 = QtWidgets.QFrame(self.page_1_quest1_2)
        self.ButtonUpperSpace_2.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace_2.setObjectName("ButtonUpperSpace_2")
        self.verticalLayout.addWidget(self.ButtonUpperSpace_2)


        self.frame_2 = QtWidgets.QFrame(self.page_1_quest1_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")


        self.btn1_2 = QtWidgets.QPushButton(self.frame_2)
        self.btn1_2.setObjectName("btn1_2")
        self.horizontalLayout_3.addWidget(self.btn1_2)
        self.btn1_2.clicked.connect(lambda: self.storyStackedWidget.setCurrentIndex(3))

        self.btn2_2 = QtWidgets.QPushButton(self.frame_2)
        self.btn2_2.setText("")
        self.btn2_2.setObjectName("btn2_2")
        self.horizontalLayout_3.addWidget(self.btn2_2)
        

        self.btn3_2 = QtWidgets.QPushButton(self.frame_2)
        self.btn3_2.setObjectName("btn3_2")
        self.horizontalLayout_3.addWidget(self.btn3_2)
        self.btn3_2.clicked.connect(lambda: self.storyStackedWidget.setCurrentIndex(1))


        self.verticalLayout.addWidget(self.frame_2)


        self.storyStackedWidget.addWidget(self.page_1_quest1_2)
        self.page_1_quest1 = QtWidgets.QWidget()
        self.page_1_quest1.setObjectName("page_1_quest1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_1_quest1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")


        self.label_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setMidLineWidth(-2)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label2_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_2.sizePolicy().hasHeightForWidth())
        self.label2_2.setSizePolicy(sizePolicy)
        self.label2_2.setAutoFillBackground(False)
        self.label2_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2_2.setMidLineWidth(-2)
        self.label2_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2_2.setObjectName("label2_2")
        self.verticalLayout_2.addWidget(self.label2_2)
        self.label3_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_2.sizePolicy().hasHeightForWidth())
        self.label3_2.setSizePolicy(sizePolicy)
        self.label3_2.setAutoFillBackground(False)
        self.label3_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3_2.setMidLineWidth(-2)
        self.label3_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3_2.setObjectName("label3_2")
        self.verticalLayout_2.addWidget(self.label3_2)
        self.label4_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_2.sizePolicy().hasHeightForWidth())
        self.label4_2.setSizePolicy(sizePolicy)
        self.label4_2.setAutoFillBackground(False)
        self.label4_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4_2.setMidLineWidth(-2)
        self.label4_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label4_2.setObjectName("label4_2")
        self.verticalLayout_2.addWidget(self.label4_2)
        self.label5_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5_2.sizePolicy().hasHeightForWidth())
        self.label5_2.setSizePolicy(sizePolicy)
        self.label5_2.setAutoFillBackground(False)
        self.label5_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5_2.setMidLineWidth(-2)
        self.label5_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5_2.setObjectName("label5_2")
        self.verticalLayout_2.addWidget(self.label5_2)
        self.label6_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6_2.sizePolicy().hasHeightForWidth())
        self.label6_2.setSizePolicy(sizePolicy)
        self.label6_2.setAutoFillBackground(False)
        self.label6_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6_2.setMidLineWidth(-2)
        self.label6_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6_2.setObjectName("label6_2")
        self.verticalLayout_2.addWidget(self.label6_2)
        self.label7_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7_2.sizePolicy().hasHeightForWidth())
        self.label7_2.setSizePolicy(sizePolicy)
        self.label7_2.setAutoFillBackground(False)
        self.label7_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7_2.setMidLineWidth(-2)
        self.label7_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7_2.setObjectName("label7_2")
        self.verticalLayout_2.addWidget(self.label7_2)
        self.label8_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8_2.sizePolicy().hasHeightForWidth())
        self.label8_2.setSizePolicy(sizePolicy)
        self.label8_2.setAutoFillBackground(False)
        self.label8_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8_2.setMidLineWidth(-2)
        self.label8_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label8_2.setObjectName("label8_2")
        self.verticalLayout_2.addWidget(self.label8_2)
        self.label9_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9_2.sizePolicy().hasHeightForWidth())
        self.label9_2.setSizePolicy(sizePolicy)
        self.label9_2.setAutoFillBackground(False)
        self.label9_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9_2.setMidLineWidth(-2)
        self.label9_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9_2.setObjectName("label9_2")
        self.verticalLayout_2.addWidget(self.label9_2)
        self.label10_2 = QtWidgets.QLabel(self.page_1_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10_2.sizePolicy().hasHeightForWidth())
        self.label10_2.setSizePolicy(sizePolicy)
        self.label10_2.setAutoFillBackground(False)
        self.label10_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10_2.setMidLineWidth(-2)
        self.label10_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10_2.setObjectName("label10_2")
        self.verticalLayout_2.addWidget(self.label10_2)
        self.ButtonUpperSpace = QtWidgets.QFrame(self.page_1_quest1)
        self.ButtonUpperSpace.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace.setObjectName("ButtonUpperSpace")
        self.verticalLayout_2.addWidget(self.ButtonUpperSpace)
        self.Buttonframe = QtWidgets.QFrame(self.page_1_quest1)
        self.Buttonframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Buttonframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Buttonframe.setObjectName("Buttonframe")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Buttonframe)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.btn1 = QtWidgets.QPushButton(self.Buttonframe)
        self.btn1.setObjectName("btn1")
        self.horizontalLayout_2.addWidget(self.btn1)
        self.btn1.clicked.connect(lambda: self.storyStackedWidget.setCurrentIndex(3))

        self.btn2 = QtWidgets.QPushButton(self.Buttonframe)
        self.btn2.setText("")
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_2.addWidget(self.btn2)

        self.btn3 = QtWidgets.QPushButton(self.Buttonframe)
        self.btn3.setObjectName("btn3")
        self.btn3.clicked.connect(lambda: self.storyStackedWidget.setCurrentIndex(2))

        self.horizontalLayout_2.addWidget(self.btn3)
        self.verticalLayout_2.addWidget(self.Buttonframe)
        self.storyStackedWidget.addWidget(self.page_1_quest1)
        self.page_2_quest1 = QtWidgets.QWidget()
        self.page_2_quest1.setObjectName("page_2_quest1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2_quest1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setMidLineWidth(-2)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.label2_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_4.sizePolicy().hasHeightForWidth())
        self.label2_4.setSizePolicy(sizePolicy)
        self.label2_4.setAutoFillBackground(False)
        self.label2_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2_4.setMidLineWidth(-2)
        self.label2_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2_4.setObjectName("label2_4")
        self.verticalLayout_4.addWidget(self.label2_4)
        self.label3_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_4.sizePolicy().hasHeightForWidth())
        self.label3_4.setSizePolicy(sizePolicy)
        self.label3_4.setAutoFillBackground(False)
        self.label3_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3_4.setMidLineWidth(-2)
        self.label3_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3_4.setObjectName("label3_4")
        self.verticalLayout_4.addWidget(self.label3_4)
        self.label4_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_4.sizePolicy().hasHeightForWidth())
        self.label4_4.setSizePolicy(sizePolicy)
        self.label4_4.setAutoFillBackground(False)
        self.label4_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4_4.setMidLineWidth(-2)
        self.label4_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label4_4.setObjectName("label4_4")
        self.verticalLayout_4.addWidget(self.label4_4)
        self.label5_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5_4.sizePolicy().hasHeightForWidth())
        self.label5_4.setSizePolicy(sizePolicy)
        self.label5_4.setAutoFillBackground(False)
        self.label5_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5_4.setMidLineWidth(-2)
        self.label5_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5_4.setObjectName("label5_4")
        self.verticalLayout_4.addWidget(self.label5_4)
        self.label6_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6_4.sizePolicy().hasHeightForWidth())
        self.label6_4.setSizePolicy(sizePolicy)
        self.label6_4.setAutoFillBackground(False)
        self.label6_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6_4.setMidLineWidth(-2)
        self.label6_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6_4.setObjectName("label6_4")
        self.verticalLayout_4.addWidget(self.label6_4)
        self.label7_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7_4.sizePolicy().hasHeightForWidth())
        self.label7_4.setSizePolicy(sizePolicy)
        self.label7_4.setAutoFillBackground(False)
        self.label7_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7_4.setMidLineWidth(-2)
        self.label7_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7_4.setObjectName("label7_4")
        self.verticalLayout_4.addWidget(self.label7_4)
        self.label8_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8_4.sizePolicy().hasHeightForWidth())
        self.label8_4.setSizePolicy(sizePolicy)
        self.label8_4.setAutoFillBackground(False)
        self.label8_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8_4.setMidLineWidth(-2)
        self.label8_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label8_4.setObjectName("label8_4")
        self.verticalLayout_4.addWidget(self.label8_4)
        self.label9_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9_4.sizePolicy().hasHeightForWidth())
        self.label9_4.setSizePolicy(sizePolicy)
        self.label9_4.setAutoFillBackground(False)
        self.label9_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9_4.setMidLineWidth(-2)
        self.label9_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9_4.setObjectName("label9_4")
        self.verticalLayout_4.addWidget(self.label9_4)
        self.label10_4 = QtWidgets.QLabel(self.page_2_quest1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10_4.sizePolicy().hasHeightForWidth())
        self.label10_4.setSizePolicy(sizePolicy)
        self.label10_4.setAutoFillBackground(False)
        self.label10_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10_4.setMidLineWidth(-2)
        self.label10_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10_4.setObjectName("label10_4")
        self.verticalLayout_4.addWidget(self.label10_4)
        self.ButtonUpperSpace_4 = QtWidgets.QFrame(self.page_2_quest1)
        self.ButtonUpperSpace_4.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace_4.setObjectName("ButtonUpperSpace_4")
        self.verticalLayout_4.addWidget(self.ButtonUpperSpace_4)
        self.Buttonframe_3 = QtWidgets.QFrame(self.page_2_quest1)
        self.Buttonframe_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Buttonframe_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Buttonframe_3.setObjectName("Buttonframe_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Buttonframe_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn1_4 = QtWidgets.QPushButton(self.Buttonframe_3)
        self.btn1_4.setObjectName("btn1_4")
        self.horizontalLayout_5.addWidget(self.btn1_4)
        self.btn1_4.clicked.connect(lambda: exit(0))

        self.btn2_4 = QtWidgets.QPushButton(self.Buttonframe_3)
        self.btn2_4.setObjectName("btn2_4")
        self.horizontalLayout_5.addWidget(self.btn2_4)
        self.btn3_4 = QtWidgets.QPushButton(self.Buttonframe_3)
        self.btn3_4.setObjectName("btn3_4")
        self.horizontalLayout_5.addWidget(self.btn3_4)
        self.verticalLayout_4.addWidget(self.Buttonframe_3)
        self.storyStackedWidget.addWidget(self.page_2_quest1)
        self.page_0_quest2 = QtWidgets.QWidget()
        self.page_0_quest2.setObjectName("page_0_quest2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_0_quest2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setMidLineWidth(-2)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label2_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_3.sizePolicy().hasHeightForWidth())
        self.label2_3.setSizePolicy(sizePolicy)
        self.label2_3.setAutoFillBackground(False)
        self.label2_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2_3.setMidLineWidth(-2)
        self.label2_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2_3.setObjectName("label2_3")
        self.verticalLayout_3.addWidget(self.label2_3)
        self.label3_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_3.sizePolicy().hasHeightForWidth())
        self.label3_3.setSizePolicy(sizePolicy)
        self.label3_3.setAutoFillBackground(False)
        self.label3_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3_3.setMidLineWidth(-2)
        self.label3_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3_3.setObjectName("label3_3")
        self.verticalLayout_3.addWidget(self.label3_3)
        self.label4_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_3.sizePolicy().hasHeightForWidth())
        self.label4_3.setSizePolicy(sizePolicy)
        self.label4_3.setAutoFillBackground(False)
        self.label4_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4_3.setMidLineWidth(-2)
        self.label4_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label4_3.setObjectName("label4_3")
        self.verticalLayout_3.addWidget(self.label4_3)
        self.label5_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5_3.sizePolicy().hasHeightForWidth())
        self.label5_3.setSizePolicy(sizePolicy)
        self.label5_3.setAutoFillBackground(False)
        self.label5_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5_3.setMidLineWidth(-2)
        self.label5_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5_3.setObjectName("label5_3")
        self.verticalLayout_3.addWidget(self.label5_3)
        self.label6_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6_3.sizePolicy().hasHeightForWidth())
        self.label6_3.setSizePolicy(sizePolicy)
        self.label6_3.setAutoFillBackground(False)
        self.label6_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6_3.setMidLineWidth(-2)
        self.label6_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6_3.setObjectName("label6_3")
        self.verticalLayout_3.addWidget(self.label6_3)
        self.label7_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7_3.sizePolicy().hasHeightForWidth())
        self.label7_3.setSizePolicy(sizePolicy)
        self.label7_3.setAutoFillBackground(False)
        self.label7_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7_3.setMidLineWidth(-2)
        self.label7_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7_3.setObjectName("label7_3")
        self.verticalLayout_3.addWidget(self.label7_3)
        self.label8_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8_3.sizePolicy().hasHeightForWidth())
        self.label8_3.setSizePolicy(sizePolicy)
        self.label8_3.setAutoFillBackground(False)
        self.label8_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8_3.setMidLineWidth(-2)
        self.label8_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label8_3.setObjectName("label8_3")
        self.verticalLayout_3.addWidget(self.label8_3)
        self.label9_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9_3.sizePolicy().hasHeightForWidth())
        self.label9_3.setSizePolicy(sizePolicy)
        self.label9_3.setAutoFillBackground(False)
        self.label9_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9_3.setMidLineWidth(-2)
        self.label9_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9_3.setObjectName("label9_3")
        self.verticalLayout_3.addWidget(self.label9_3)
        self.label10_3 = QtWidgets.QLabel(self.page_0_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10_3.sizePolicy().hasHeightForWidth())
        self.label10_3.setSizePolicy(sizePolicy)
        self.label10_3.setAutoFillBackground(False)
        self.label10_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10_3.setMidLineWidth(-2)
        self.label10_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10_3.setObjectName("label10_3")
        self.verticalLayout_3.addWidget(self.label10_3)
        self.ButtonUpperSpace_3 = QtWidgets.QFrame(self.page_0_quest2)
        self.ButtonUpperSpace_3.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace_3.setObjectName("ButtonUpperSpace_3")
        self.verticalLayout_3.addWidget(self.ButtonUpperSpace_3)
        self.Buttonframe_2 = QtWidgets.QFrame(self.page_0_quest2)
        self.Buttonframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Buttonframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Buttonframe_2.setObjectName("Buttonframe_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Buttonframe_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn1_3 = QtWidgets.QPushButton(self.Buttonframe_2)
        self.btn1_3.setObjectName("btn1_3")
        self.horizontalLayout_4.addWidget(self.btn1_3)
        self.btn1_3.clicked.connect(
            lambda: self.storyStackedWidget.setCurrentIndex(4))

        self.btn2_3 = QtWidgets.QPushButton(self.Buttonframe_2)
        self.btn2_3.setObjectName("btn2_3")
        self.horizontalLayout_4.addWidget(self.btn2_3)
        self.btn2_3.clicked.connect(lambda: self.storyStackedWidget.setCurrentIndex(5))

        self.btn3_3 = QtWidgets.QPushButton(self.Buttonframe_2)
        self.btn3_3.setObjectName("btn3_3")
        self.horizontalLayout_4.addWidget(self.btn3_3)
        self.btn3_3.clicked.connect(lambda: self.storyStackedWidget.setCurrentIndex(6))

        self.verticalLayout_3.addWidget(self.Buttonframe_2)
        self.storyStackedWidget.addWidget(self.page_0_quest2)
        self.page_1_quest2 = QtWidgets.QWidget()
        self.page_1_quest2.setObjectName("page_1_quest2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_1_quest2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label1_2 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_2.sizePolicy().hasHeightForWidth())
        self.label1_2.setSizePolicy(sizePolicy)
        self.label1_2.setAutoFillBackground(False)
        self.label1_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_2.setMidLineWidth(-2)
        self.label1_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label1_2.setObjectName("label1_2")
        self.verticalLayout_5.addWidget(self.label1_2)
        self.label2_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_5.sizePolicy().hasHeightForWidth())
        self.label2_5.setSizePolicy(sizePolicy)
        self.label2_5.setAutoFillBackground(False)
        self.label2_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2_5.setMidLineWidth(-2)
        self.label2_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2_5.setObjectName("label2_5")
        self.verticalLayout_5.addWidget(self.label2_5)
        self.label3_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_5.sizePolicy().hasHeightForWidth())
        self.label3_5.setSizePolicy(sizePolicy)
        self.label3_5.setAutoFillBackground(False)
        self.label3_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3_5.setMidLineWidth(-2)
        self.label3_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3_5.setObjectName("label3_5")
        self.verticalLayout_5.addWidget(self.label3_5)
        self.label4_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_5.sizePolicy().hasHeightForWidth())
        self.label4_5.setSizePolicy(sizePolicy)
        self.label4_5.setAutoFillBackground(False)
        self.label4_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4_5.setMidLineWidth(-2)
        self.label4_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label4_5.setObjectName("label4_5")
        self.verticalLayout_5.addWidget(self.label4_5)
        self.label5_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5_5.sizePolicy().hasHeightForWidth())
        self.label5_5.setSizePolicy(sizePolicy)
        self.label5_5.setAutoFillBackground(False)
        self.label5_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5_5.setMidLineWidth(-2)
        self.label5_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5_5.setObjectName("label5_5")
        self.verticalLayout_5.addWidget(self.label5_5)
        self.label6_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6_5.sizePolicy().hasHeightForWidth())
        self.label6_5.setSizePolicy(sizePolicy)
        self.label6_5.setAutoFillBackground(False)
        self.label6_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6_5.setMidLineWidth(-2)
        self.label6_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6_5.setObjectName("label6_5")
        self.verticalLayout_5.addWidget(self.label6_5)
        self.label7_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7_5.sizePolicy().hasHeightForWidth())
        self.label7_5.setSizePolicy(sizePolicy)
        self.label7_5.setAutoFillBackground(False)
        self.label7_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7_5.setMidLineWidth(-2)
        self.label7_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7_5.setObjectName("label7_5")
        self.verticalLayout_5.addWidget(self.label7_5)
        self.label8_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8_5.sizePolicy().hasHeightForWidth())
        self.label8_5.setSizePolicy(sizePolicy)
        self.label8_5.setAutoFillBackground(False)
        self.label8_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8_5.setMidLineWidth(-2)
        self.label8_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label8_5.setObjectName("label8_5")
        self.verticalLayout_5.addWidget(self.label8_5)
        self.label9_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9_5.sizePolicy().hasHeightForWidth())
        self.label9_5.setSizePolicy(sizePolicy)
        self.label9_5.setAutoFillBackground(False)
        self.label9_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9_5.setMidLineWidth(-2)
        self.label9_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9_5.setObjectName("label9_5")
        self.verticalLayout_5.addWidget(self.label9_5)
        self.label10_5 = QtWidgets.QLabel(self.page_1_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10_5.sizePolicy().hasHeightForWidth())
        self.label10_5.setSizePolicy(sizePolicy)
        self.label10_5.setAutoFillBackground(False)
        self.label10_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10_5.setMidLineWidth(-2)
        self.label10_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10_5.setObjectName("label10_5")
        self.verticalLayout_5.addWidget(self.label10_5)
        self.ButtonUpperSpace_5 = QtWidgets.QFrame(self.page_1_quest2)
        self.ButtonUpperSpace_5.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace_5.setObjectName("ButtonUpperSpace_5")
        self.verticalLayout_5.addWidget(self.ButtonUpperSpace_5)
        self.frame_3 = QtWidgets.QFrame(self.page_1_quest2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn1_5 = QtWidgets.QPushButton(self.frame_3)
        self.btn1_5.setObjectName("btn1_5")
        self.horizontalLayout_6.addWidget(self.btn1_5)
        self.btn2_5 = QtWidgets.QPushButton(self.frame_3)
        self.btn2_5.setObjectName("btn2_5")
        self.horizontalLayout_6.addWidget(self.btn2_5)
        self.btn3_5 = QtWidgets.QPushButton(self.frame_3)
        self.btn3_5.setObjectName("btn3_5")
        self.horizontalLayout_6.addWidget(self.btn3_5)
        self.verticalLayout_5.addWidget(self.frame_3)
        self.storyStackedWidget.addWidget(self.page_1_quest2)
        self.page_2_quest2 = QtWidgets.QWidget()
        self.page_2_quest2.setObjectName("page_2_quest2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2_quest2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label1_3 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_3.sizePolicy().hasHeightForWidth())
        self.label1_3.setSizePolicy(sizePolicy)
        self.label1_3.setAutoFillBackground(False)
        self.label1_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_3.setMidLineWidth(-2)
        self.label1_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label1_3.setObjectName("label1_3")
        self.verticalLayout_6.addWidget(self.label1_3)
        self.label2_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_6.sizePolicy().hasHeightForWidth())
        self.label2_6.setSizePolicy(sizePolicy)
        self.label2_6.setAutoFillBackground(False)
        self.label2_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2_6.setMidLineWidth(-2)
        self.label2_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2_6.setObjectName("label2_6")
        self.verticalLayout_6.addWidget(self.label2_6)
        self.label3_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_6.sizePolicy().hasHeightForWidth())
        self.label3_6.setSizePolicy(sizePolicy)
        self.label3_6.setAutoFillBackground(False)
        self.label3_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3_6.setMidLineWidth(-2)
        self.label3_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3_6.setObjectName("label3_6")
        self.verticalLayout_6.addWidget(self.label3_6)
        self.label4_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_6.sizePolicy().hasHeightForWidth())
        self.label4_6.setSizePolicy(sizePolicy)
        self.label4_6.setAutoFillBackground(False)
        self.label4_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4_6.setMidLineWidth(-2)
        self.label4_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label4_6.setObjectName("label4_6")
        self.verticalLayout_6.addWidget(self.label4_6)
        self.label5_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5_6.sizePolicy().hasHeightForWidth())
        self.label5_6.setSizePolicy(sizePolicy)
        self.label5_6.setAutoFillBackground(False)
        self.label5_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5_6.setMidLineWidth(-2)
        self.label5_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5_6.setObjectName("label5_6")
        self.verticalLayout_6.addWidget(self.label5_6)
        self.label6_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6_6.sizePolicy().hasHeightForWidth())
        self.label6_6.setSizePolicy(sizePolicy)
        self.label6_6.setAutoFillBackground(False)
        self.label6_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6_6.setMidLineWidth(-2)
        self.label6_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6_6.setObjectName("label6_6")
        self.verticalLayout_6.addWidget(self.label6_6)
        self.label7_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7_6.sizePolicy().hasHeightForWidth())
        self.label7_6.setSizePolicy(sizePolicy)
        self.label7_6.setAutoFillBackground(False)
        self.label7_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7_6.setMidLineWidth(-2)
        self.label7_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7_6.setObjectName("label7_6")
        self.verticalLayout_6.addWidget(self.label7_6)
        self.label8_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8_6.sizePolicy().hasHeightForWidth())
        self.label8_6.setSizePolicy(sizePolicy)
        self.label8_6.setAutoFillBackground(False)
        self.label8_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8_6.setMidLineWidth(-2)
        self.label8_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label8_6.setObjectName("label8_6")
        self.verticalLayout_6.addWidget(self.label8_6)
        self.label9_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9_6.sizePolicy().hasHeightForWidth())
        self.label9_6.setSizePolicy(sizePolicy)
        self.label9_6.setAutoFillBackground(False)
        self.label9_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9_6.setMidLineWidth(-2)
        self.label9_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9_6.setObjectName("label9_6")
        self.verticalLayout_6.addWidget(self.label9_6)
        self.label10_6 = QtWidgets.QLabel(self.page_2_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10_6.sizePolicy().hasHeightForWidth())
        self.label10_6.setSizePolicy(sizePolicy)
        self.label10_6.setAutoFillBackground(False)
        self.label10_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10_6.setMidLineWidth(-2)
        self.label10_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10_6.setObjectName("label10_6")
        self.verticalLayout_6.addWidget(self.label10_6)
        self.ButtonUpperSpace_6 = QtWidgets.QFrame(self.page_2_quest2)
        self.ButtonUpperSpace_6.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace_6.setObjectName("ButtonUpperSpace_6")
        self.verticalLayout_6.addWidget(self.ButtonUpperSpace_6)
        self.frame_4 = QtWidgets.QFrame(self.page_2_quest2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn1_6 = QtWidgets.QPushButton(self.frame_4)
        self.btn1_6.setObjectName("btn1_6")
        self.horizontalLayout_7.addWidget(self.btn1_6)
        self.btn2_6 = QtWidgets.QPushButton(self.frame_4)
        self.btn2_6.setObjectName("btn2_6")
        self.horizontalLayout_7.addWidget(self.btn2_6)
        self.btn3_6 = QtWidgets.QPushButton(self.frame_4)
        self.btn3_6.setObjectName("btn3_6")
        self.horizontalLayout_7.addWidget(self.btn3_6)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.storyStackedWidget.addWidget(self.page_2_quest2)
        self.page_3_quest2 = QtWidgets.QWidget()
        self.page_3_quest2.setObjectName("page_3_quest2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_3_quest2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label1_4 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_4.sizePolicy().hasHeightForWidth())
        self.label1_4.setSizePolicy(sizePolicy)
        self.label1_4.setAutoFillBackground(False)
        self.label1_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_4.setMidLineWidth(-2)
        self.label1_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label1_4.setObjectName("label1_4")
        self.verticalLayout_7.addWidget(self.label1_4)
        self.label2_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_7.sizePolicy().hasHeightForWidth())
        self.label2_7.setSizePolicy(sizePolicy)
        self.label2_7.setAutoFillBackground(False)
        self.label2_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2_7.setMidLineWidth(-2)
        self.label2_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2_7.setObjectName("label2_7")
        self.verticalLayout_7.addWidget(self.label2_7)
        self.label3_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_7.sizePolicy().hasHeightForWidth())
        self.label3_7.setSizePolicy(sizePolicy)
        self.label3_7.setAutoFillBackground(False)
        self.label3_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3_7.setMidLineWidth(-2)
        self.label3_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3_7.setObjectName("label3_7")
        self.verticalLayout_7.addWidget(self.label3_7)
        self.label4_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_7.sizePolicy().hasHeightForWidth())
        self.label4_7.setSizePolicy(sizePolicy)
        self.label4_7.setAutoFillBackground(False)
        self.label4_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4_7.setMidLineWidth(-2)
        self.label4_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label4_7.setObjectName("label4_7")
        self.verticalLayout_7.addWidget(self.label4_7)
        self.label5_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5_7.sizePolicy().hasHeightForWidth())
        self.label5_7.setSizePolicy(sizePolicy)
        self.label5_7.setAutoFillBackground(False)
        self.label5_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5_7.setMidLineWidth(-2)
        self.label5_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5_7.setObjectName("label5_7")
        self.verticalLayout_7.addWidget(self.label5_7)
        self.label6_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6_7.sizePolicy().hasHeightForWidth())
        self.label6_7.setSizePolicy(sizePolicy)
        self.label6_7.setAutoFillBackground(False)
        self.label6_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6_7.setMidLineWidth(-2)
        self.label6_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6_7.setObjectName("label6_7")
        self.verticalLayout_7.addWidget(self.label6_7)
        self.label7_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7_7.sizePolicy().hasHeightForWidth())
        self.label7_7.setSizePolicy(sizePolicy)
        self.label7_7.setAutoFillBackground(False)
        self.label7_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7_7.setMidLineWidth(-2)
        self.label7_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7_7.setObjectName("label7_7")
        self.verticalLayout_7.addWidget(self.label7_7)
        self.label8_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8_7.sizePolicy().hasHeightForWidth())
        self.label8_7.setSizePolicy(sizePolicy)
        self.label8_7.setAutoFillBackground(False)
        self.label8_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8_7.setMidLineWidth(-2)
        self.label8_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label8_7.setObjectName("label8_7")
        self.verticalLayout_7.addWidget(self.label8_7)
        self.label9_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9_7.sizePolicy().hasHeightForWidth())
        self.label9_7.setSizePolicy(sizePolicy)
        self.label9_7.setAutoFillBackground(False)
        self.label9_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9_7.setMidLineWidth(-2)
        self.label9_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9_7.setObjectName("label9_7")
        self.verticalLayout_7.addWidget(self.label9_7)
        self.label10_7 = QtWidgets.QLabel(self.page_3_quest2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10_7.sizePolicy().hasHeightForWidth())
        self.label10_7.setSizePolicy(sizePolicy)
        self.label10_7.setAutoFillBackground(False)
        self.label10_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10_7.setMidLineWidth(-2)
        self.label10_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10_7.setObjectName("label10_7")
        self.verticalLayout_7.addWidget(self.label10_7)
        self.ButtonUpperSpace_7 = QtWidgets.QFrame(self.page_3_quest2)
        self.ButtonUpperSpace_7.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace_7.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace_7.setObjectName("ButtonUpperSpace_7")
        self.verticalLayout_7.addWidget(self.ButtonUpperSpace_7)
        self.frame_5 = QtWidgets.QFrame(self.page_3_quest2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn1_7 = QtWidgets.QPushButton(self.frame_5)
        self.btn1_7.setObjectName("btn1_7")
        self.horizontalLayout_8.addWidget(self.btn1_7)
        self.btn2_7 = QtWidgets.QPushButton(self.frame_5)
        self.btn2_7.setObjectName("btn2_7")
        self.horizontalLayout_8.addWidget(self.btn2_7)
        self.btn3_7 = QtWidgets.QPushButton(self.frame_5)
        self.btn3_7.setObjectName("btn3_7")
        self.horizontalLayout_8.addWidget(self.btn3_7)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.storyStackedWidget.addWidget(self.page_3_quest2)
        self.page_0_quest3 = QtWidgets.QWidget()
        self.page_0_quest3.setObjectName("page_0_quest3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_0_quest3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label1_5 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1_5.sizePolicy().hasHeightForWidth())
        self.label1_5.setSizePolicy(sizePolicy)
        self.label1_5.setAutoFillBackground(False)
        self.label1_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label1_5.setMidLineWidth(-2)
        self.label1_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label1_5.setObjectName("label1_5")
        self.verticalLayout_8.addWidget(self.label1_5)
        self.label2_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2_8.sizePolicy().hasHeightForWidth())
        self.label2_8.setSizePolicy(sizePolicy)
        self.label2_8.setAutoFillBackground(False)
        self.label2_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label2_8.setMidLineWidth(-2)
        self.label2_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label2_8.setObjectName("label2_8")
        self.verticalLayout_8.addWidget(self.label2_8)
        self.label3_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3_8.sizePolicy().hasHeightForWidth())
        self.label3_8.setSizePolicy(sizePolicy)
        self.label3_8.setAutoFillBackground(False)
        self.label3_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label3_8.setMidLineWidth(-2)
        self.label3_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label3_8.setObjectName("label3_8")
        self.verticalLayout_8.addWidget(self.label3_8)
        self.label4_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4_8.sizePolicy().hasHeightForWidth())
        self.label4_8.setSizePolicy(sizePolicy)
        self.label4_8.setAutoFillBackground(False)
        self.label4_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label4_8.setMidLineWidth(-2)
        self.label4_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label4_8.setObjectName("label4_8")
        self.verticalLayout_8.addWidget(self.label4_8)
        self.label5_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5_8.sizePolicy().hasHeightForWidth())
        self.label5_8.setSizePolicy(sizePolicy)
        self.label5_8.setAutoFillBackground(False)
        self.label5_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label5_8.setMidLineWidth(-2)
        self.label5_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label5_8.setObjectName("label5_8")
        self.verticalLayout_8.addWidget(self.label5_8)
        self.label6_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6_8.sizePolicy().hasHeightForWidth())
        self.label6_8.setSizePolicy(sizePolicy)
        self.label6_8.setAutoFillBackground(False)
        self.label6_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label6_8.setMidLineWidth(-2)
        self.label6_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label6_8.setObjectName("label6_8")
        self.verticalLayout_8.addWidget(self.label6_8)
        self.label7_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7_8.sizePolicy().hasHeightForWidth())
        self.label7_8.setSizePolicy(sizePolicy)
        self.label7_8.setAutoFillBackground(False)
        self.label7_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label7_8.setMidLineWidth(-2)
        self.label7_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label7_8.setObjectName("label7_8")
        self.verticalLayout_8.addWidget(self.label7_8)
        self.label8_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8_8.sizePolicy().hasHeightForWidth())
        self.label8_8.setSizePolicy(sizePolicy)
        self.label8_8.setAutoFillBackground(False)
        self.label8_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label8_8.setMidLineWidth(-2)
        self.label8_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label8_8.setObjectName("label8_8")
        self.verticalLayout_8.addWidget(self.label8_8)
        self.label9_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9_8.sizePolicy().hasHeightForWidth())
        self.label9_8.setSizePolicy(sizePolicy)
        self.label9_8.setAutoFillBackground(False)
        self.label9_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label9_8.setMidLineWidth(-2)
        self.label9_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label9_8.setObjectName("label9_8")
        self.verticalLayout_8.addWidget(self.label9_8)
        self.label10_8 = QtWidgets.QLabel(self.page_0_quest3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10_8.sizePolicy().hasHeightForWidth())
        self.label10_8.setSizePolicy(sizePolicy)
        self.label10_8.setAutoFillBackground(False)
        self.label10_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label10_8.setMidLineWidth(-2)
        self.label10_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label10_8.setObjectName("label10_8")
        self.verticalLayout_8.addWidget(self.label10_8)
        self.ButtonUpperSpace_8 = QtWidgets.QFrame(self.page_0_quest3)
        self.ButtonUpperSpace_8.setMinimumSize(QtCore.QSize(0, 50))
        self.ButtonUpperSpace_8.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ButtonUpperSpace_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonUpperSpace_8.setObjectName("ButtonUpperSpace_8")
        self.verticalLayout_8.addWidget(self.ButtonUpperSpace_8)
        self.frame_6 = QtWidgets.QFrame(self.page_0_quest3)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btn1_8 = QtWidgets.QPushButton(self.frame_6)
        self.btn1_8.setObjectName("btn1_8")
        self.horizontalLayout_9.addWidget(self.btn1_8)
        self.btn2_8 = QtWidgets.QPushButton(self.frame_6)
        self.btn2_8.setObjectName("btn2_8")
        self.horizontalLayout_9.addWidget(self.btn2_8)
        self.btn3_8 = QtWidgets.QPushButton(self.frame_6)
        self.btn3_8.setObjectName("btn3_8")
        self.horizontalLayout_9.addWidget(self.btn3_8)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.storyStackedWidget.addWidget(self.page_0_quest3)
        self.gridLayout.addWidget(self.storyStackedWidget, 1, 0, 1, 2)
        self.ButtonBottomSpace = QtWidgets.QFrame(self.centralwidget)
        self.ButtonBottomSpace.setMinimumSize(QtCore.QSize(0, 15))
        self.ButtonBottomSpace.setMaximumSize(QtCore.QSize(16777215, 15))
        self.ButtonBottomSpace.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonBottomSpace.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonBottomSpace.setObjectName("ButtonBottomSpace")
        self.gridLayout.addWidget(self.ButtonBottomSpace, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.storyStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _trns_ = QtCore.QCoreApplication.translate
        mw = "MainWindow"
        MainWindow.setWindowTitle(_trns_(mw, "Sushi\'s Life: Tiny Adventure"))

        # start text
        self.label1.setText(_trns_(mw, qna.tellme(3)))
        self.label2.setText(_trns_(mw, qna.tellme(4)))
        self.label3.setText(_trns_(mw, ''))
        self.label4.setText(_trns_(mw, ''))
        self.label5.setText(_trns_(mw, ''))
        self.label6.setText(_trns_(mw, ''))
        self.label7.setText(_trns_(mw, ''))
        self.label8.setText(_trns_(mw, ''))
        self.label9.setText(_trns_(mw, ''))
        self.label10.setText(_trns_(mw, ''))
        # start buttons (only two)
        self.btn1_2.setText(_trns_(mw, "Wake up sleepy head!"))
        self.btn3_2.setText(_trns_(mw, "Let them sleep"))


        # start path answer "Let them sleep"
        self.label_2.setText(_trns_(mw, qna.tellme(11)))
        self.label2_2.setText(_trns_(mw, ''))
        self.label3_2.setText(_trns_(mw, ''))
        self.label4_2.setText(_trns_(mw, ''))
        self.label5_2.setText(_trns_(mw, ''))
        self.label6_2.setText(_trns_(mw, ''))
        self.label7_2.setText(_trns_(mw, ''))
        self.label8_2.setText(_trns_(mw, ''))
        self.label9_2.setText(_trns_(mw, ''))
        self.label10_2.setText(_trns_(mw, ''))
        # start path answer "Let them sleep" -> Last Chance
        self.btn1.setText(_trns_(mw, "Wake up sleepy head!"))
        self.btn3.setText(_trns_(mw, "Let them sleep some more?"))


        # start path answer 2 "Let them sleep some more?" -> Game Over
        self.label_4.setText(_trns_(mw, "The cat sleeps all day, goodbye adventure!"))
        self.label2_4.setText(_trns_(mw, ""))
        self.label3_4.setText(_trns_(mw, ""))
        self.label4_4.setText(_trns_(mw, ""))
        self.label5_4.setText(_trns_(mw, ""))
        self.label6_4.setText(_trns_(mw, ""))
        self.label7_4.setText(_trns_(mw, ""))
        self.label8_4.setText(_trns_(mw, ""))
        self.label9_4.setText(_trns_(mw, ""))
        self.label10_4.setText(_trns_(mw, ""))

        self.btn1_4.setText(_trns_(mw, "Exit"))
        self.btn2_4.setText(_trns_(mw, ""))
        self.btn3_4.setText(_trns_(mw, ""))

        # start path answer "Wake up sleepy head!"
        # scene 1 question 1
        self.label_3.setText(_trns_(mw, qna.tellme(15)))
        self.label2_3.setText(_trns_(mw, qna.tellme(16)))
        self.label3_3.setText(_trns_(mw, qna.tellme(17)))
        self.label4_3.setText(_trns_(mw, qna.tellme(18)))
        self.label5_3.setText(_trns_(mw, qna.tellme(19)))
        self.label6_3.setText(_trns_(mw, ''))
        self.label7_3.setText(_trns_(mw, ''))
        self.label8_3.setText(_trns_(mw, ''))
        self.label9_3.setText(_trns_(mw, ''))
        self.label10_3.setText(_trns_(mw, ''))

        self.btn1_3.setText(_trns_(mw, "Bump into her hand, pets!"))
        self.btn2_3.setText(_trns_(mw, "Back away."))
        self.btn3_3.setText(_trns_(mw, "Don\'t do anything."))

        # scene 1 answ 1
        self.label1_2.setText(_trns_(mw, qna.tellme(21)))
        self.label2_5.setText(_trns_(mw, qna.tellme(22)))
        self.label3_5.setText(_trns_(mw, qna.tellme(23)))
        self.label4_5.setText(_trns_(mw, qna.tellme(24)))
        self.label5_5.setText(_trns_(mw, qna.tellme(25)))
        self.label6_5.setText(_trns_(mw, qna.tellme(26)))
        self.label7_5.setText(_trns_(mw, qna.tellme(27)))
        self.label8_5.setText(_trns_(mw, qna.tellme(28)))
        self.label9_5.setText(_trns_(mw, ''))
        self.label10_5.setText(_trns_(mw, ''))

        self.btn1_5.setText(_trns_(mw, "SOON?"))
        self.btn2_5.setText(_trns_(mw, "SOON?"))
        self.btn3_5.setText(_trns_(mw, "SOON?"))

        # scene 1 answ 2
        self.label1_3.setText(_trns_(mw, qna.tellme(30)))
        self.label2_6.setText(_trns_(mw, qna.tellme(31)))
        self.label3_6.setText(_trns_(mw, qna.tellme(32)))
        self.label4_6.setText(_trns_(mw, qna.tellme(33)))
        self.label5_6.setText(_trns_(mw, qna.tellme(34)))
        self.label6_6.setText(_trns_(mw, qna.tellme(35)))
        self.label7_6.setText(_trns_(mw, qna.tellme(36)))
        self.label8_6.setText(_trns_(mw, ''))
        self.label9_6.setText(_trns_(mw, ''))
        self.label10_6.setText(_trns_(mw, ''))

        self.btn1_6.setText(_trns_(mw, "SOON?"))
        self.btn2_6.setText(_trns_(mw, "SOON?"))
        self.btn3_6.setText(_trns_(mw, "SOON?"))

        # scene 1 answ 3
        self.label1_4.setText(_trns_(mw, qna.tellme(38)))
        self.label2_7.setText(_trns_(mw, qna.tellme(39)))
        self.label3_7.setText(_trns_(mw, ""))
        self.label4_7.setText(_trns_(mw, ""))
        self.label5_7.setText(_trns_(mw, ""))
        self.label6_7.setText(_trns_(mw, ""))
        self.label7_7.setText(_trns_(mw, ""))
        self.label8_7.setText(_trns_(mw, ""))
        self.label9_7.setText(_trns_(mw, ""))
        self.label10_7.setText(_trns_(mw, ""))

        self.btn1_7.setText(_trns_(mw, "SOON?"))
        self.btn2_7.setText(_trns_(mw, "SOON?"))
        self.btn3_7.setText(_trns_(mw, "SOON?"))


        self.label1_5.setText(_trns_(mw, ""))
        self.label2_8.setText(_trns_(mw, ""))
        self.label3_8.setText(_trns_(mw, ""))
        self.label4_8.setText(_trns_(mw, ""))
        self.label5_8.setText(_trns_(mw, ""))
        self.label6_8.setText(_trns_(mw, ""))
        self.label7_8.setText(_trns_(mw, ""))
        self.label8_8.setText(_trns_(mw, ""))
        self.label9_8.setText(_trns_(mw, ""))
        self.label10_8.setText(_trns_(mw, "If you are here you must be a 1000 IQ hacker"))

        self.btn1_8.setText(_trns_(mw, "Go"))
        self.btn2_8.setText(_trns_(mw, "Away"))
        self.btn3_8.setText(_trns_(mw, "Nerd"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)
